@Service01.API_HostAddress = http://localhost:5019

GET {{Service01.API_HostAddress}}/health/
Accept: application/json

###

GET {{Service01.API_HostAddress}}/metrics/
Accept: application/json

###

GET {{Service01.API_HostAddress}}/api/rate/USD/EUR/001
Accept: application/json
###
GET {{Service01.API_HostAddress}}/api/rate/USD/EUR/002
Accept: application/json
###
GET {{Service01.API_HostAddress}}/api/rate/CAD/RUB/001
Accept: application/json
###
GET {{Service01.API_HostAddress}}/api/rate/CAD/RUB/002
Accept: application/json